const express = require('express');
const auth = require('../middlewares/authMiddleware');
const controller = require('../controllers/financialAccountController');
const router = express.Router();
router.use(auth);
router.get('/', controller.list);
router.post('/', controller.create);
router.post('/transfers', controller.transfer);
router.post('/adjustments', controller.adjustment);
router.post('/closings', controller.close);
router.get('/closings', controller.closings);
router.post('/movements/:id/reverse', controller.reverse);
router.patch('/:id', controller.update);
router.get('/statement', controller.statement);
module.exports = router;
