const express = require('express');
const controller = require('../controllers/loanController');
const router = express.Router();
router.get('/configurations', controller.configurations);
router.put('/configurations', controller.saveConfiguration);
router.get('/settings', controller.getSettings);
router.put('/settings', controller.updateSettings);
router.get('/settings/holidays', controller.holidays);
router.post('/settings/holidays', controller.createHoliday);
router.put('/settings/holidays/:id', controller.updateHoliday);
router.delete('/settings/holidays/:id', controller.deleteHoliday);
router.get('/customers', controller.customers);
router.post('/simulate', controller.simulate);
router.post('/', controller.create);
module.exports = router;
