const bcrypt = require('bcrypt');
const prisma = require('../config/database');
const HttpError = require('../utils/httpError');
const { memberCreateSchema, memberUpdateSchema, idSchema } = require('../utils/validators');
const { publicUser, serialize } = require('../utils/serializers');
const { sendSuccess } = require('../utils/responseHelper');

function owner(req) { return req.workspaceOwner?.id || req.user.id; }
function requireAdmin(req) { if (req.actor?.role !== 'ADMIN') throw new HttpError(403, 'ADMIN_REQUIRED', 'Apenas administradores podem gerenciar acessos.'); }
async function me(req, res) { const actor = req.actor || req.user; return sendSuccess(res, { user: publicUser(actor), workspaceOwnerId: owner(req), customerId: actor.clientProfile?.id || null }); }
async function list(req, res) { requireAdmin(req); const users = await prisma.user.findMany({ where: { OR: [{ id: owner(req) }, { workspaceOwnerId: owner(req) }] }, select: { id: true, name: true, email: true, phone: true, role: true, workspaceOwnerId: true, clientProfile: { select: { id: true, name: true } }, assignedCustomers: { select: { id: true, name: true } } }, orderBy: { createdAt: 'asc' } }); return sendSuccess(res, serialize(users)); }
async function create(req, res) { requireAdmin(req); const input = memberCreateSchema.parse(req.body); const workspaceOwnerId = owner(req); if (input.role === 'CLIENT' && !input.customerId) throw new HttpError(400, 'CUSTOMER_REQUIRED', 'Associe o perfil Cliente a uma pessoa.'); const customer = input.customerId ? await prisma.customer.findFirst({ where: { id: input.customerId, userId: workspaceOwnerId } }) : null; if (input.customerId && !customer) throw new HttpError(404, 'CUSTOMER_NOT_FOUND', 'Pessoa não encontrada neste espaço.'); const user = await prisma.user.create({ data: { name: input.name, email: input.email, password: await bcrypt.hash(input.password, 12), role: input.role, workspaceOwnerId } }); if (input.role === 'CLIENT') await prisma.customer.update({ where: { id: input.customerId }, data: { portalUserId: user.id } }); return sendSuccess(res, publicUser(user), 'Acesso criado com sucesso.', 201); }
async function update(req, res) { requireAdmin(req); const targetId = idSchema.parse(req.params).id; const input = memberUpdateSchema.parse(req.body); const workspaceOwnerId = owner(req); const member = await prisma.user.findFirst({ where: { id: targetId, workspaceOwnerId } }); if (!member) throw new HttpError(404, 'MEMBER_NOT_FOUND', 'Membro não encontrado.'); if (input.customerId) { const customer = await prisma.customer.findFirst({ where: { id: input.customerId, userId: workspaceOwnerId } }); if (!customer) throw new HttpError(404, 'CUSTOMER_NOT_FOUND', 'Pessoa não encontrada neste espaço.'); }
  await prisma.$transaction(async (tx) => { if (input.role || Object.prototype.hasOwnProperty.call(input, 'customerId')) await tx.user.update({ where: { id: member.id }, data: input.role ? { role: input.role } : {} }); if (Object.prototype.hasOwnProperty.call(input, 'customerId')) { await tx.customer.updateMany({ where: { portalUserId: member.id }, data: { portalUserId: null } }); if (input.customerId) await tx.customer.update({ where: { id: input.customerId }, data: { portalUserId: member.id } }); } if (input.customerIds) { await tx.customer.updateMany({ where: { userId: workspaceOwnerId, collectorId: member.id }, data: { collectorId: null } }); if (input.customerIds.length) await tx.customer.updateMany({ where: { id: { in: input.customerIds }, userId: workspaceOwnerId }, data: { collectorId: member.id } }); } }); return sendSuccess(res, null, 'Acesso atualizado com sucesso.'); }

module.exports = { me, list, create, update };
